#use database name
#db.createCollection("Reservation"); 
server:
  port: 1234
spring:
  data:
    mongodb:
      uri:  mongodb://127.0.0.1:27017
      host: localhost
      port: 27017
      database: RRdb